/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as NewPasswordRouteImport } from './routes/new-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecoveryVerifyRouteImport } from './routes/recovery-verify'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const NewPasswordRoute = NewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryVerifyRoute = RecoveryVerifyRouteImport.update({
  id: '/recovery-verify',
  path: '/recovery-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/new-password': typeof NewPasswordRoute
  '/profile': typeof ProfileRoute
  '/recovery-verify': typeof RecoveryVerifyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/new-password': typeof NewPasswordRoute
  '/profile': typeof ProfileRoute
  '/recovery-verify': typeof RecoveryVerifyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/cases': typeof CasesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/follow-ups': typeof FollowUpsRoute
  '/new-password': typeof NewPasswordRoute
  '/profile': typeof ProfileRoute
  '/recovery-verify': typeof RecoveryVerifyRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/cases'
    | '/dashboard'
    | '/follow-ups'
    | '/new-password'
    | '/profile'
    | '/recovery-verify'
    | '/reports'
    | '/reset-password'
    | '/verify'
    | '/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/cases'
    | '/dashboard'
    | '/follow-ups'
    | '/new-password'
    | '/profile'
    | '/recovery-verify'
    | '/reports'
    | '/reset-password'
    | '/verify'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/cases'
    | '/dashboard'
    | '/follow-ups'
    | '/new-password'
    | '/profile'
    | '/recovery-verify'
    | '/reports'
    | '/reset-password'
    | '/verify'
    | '/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CasesRoute: typeof CasesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FollowUpsRoute: typeof FollowUpsRoute
  NewPasswordRoute: typeof NewPasswordRoute
  ProfileRoute: typeof ProfileRoute
  RecoveryVerifyRoute: typeof RecoveryVerifyRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-password': {
      id: '/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof NewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-verify': {
      id: '/recovery-verify'
      path: '/recovery-verify'
      fullPath: '/recovery-verify'
      preLoaderRoute: typeof RecoveryVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
  }
}

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CasesRoute: CasesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FollowUpsRoute: FollowUpsRoute,
  NewPasswordRoute: NewPasswordRoute,
  ProfileRoute: ProfileRoute,
  RecoveryVerifyRoute: RecoveryVerifyRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
